### ISSUE TITLE
Migrate strongswan module to Vox Pupuli

### ISSUE THREAD

**Issue by CommanderK5** [voxpupuli/puppet-strongswan#2]
This module will be migrated to Vox Pupuli:

- [x] Ask one of the Administrators to add you to the modules/admin team.
- [x]  At that point you can transfer your own repository
- [x]  If migrating a module from puppetlabs, re-enable github issues.
- [x]  Verify that all webhooks except travis are disabled.
- [x]  Update the README.md with a description of the deprecation and a link to the new module location.
- [x]  Release a 999.999.999 version of the original module to the forge, so users and tools knows to stop using it.
- [x]  Release a copy of your module to the ‘puppet’ forge account.
- [x]  Add the module to our modulesync setup
- [x]  Add the module to our plumbing repository(handles travis secrets)
- [x]  Ask one of the Admins to add the module to the collaborators Team on github.
- [x] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well)
- [x] Sync labels

**Comment by bastelfreak** [comment]
oh we really need to continue. I will try to add it to my todo list for the upcoming days

**Comment by CommanderK5** [comment]
@bastelfreak Hey, sorry about that, will manage some time this week to complete the migration. Could you advice on the next step?

**Comment by rnelson0** [comment]
@CommanderK5 There's a guide for [first time publishing setup](https://voxpupuli.org/docs/#publishing-a-module---setup).
* If you can get on irc, or if you get @bastelfreak on slack today, getting the secret will go faster.
* The rest is going through the modulesync process, which is not that difficult but sometimes takes a few tries to get the cadence right.
* Once tests return to green, then we just to [publish a release](https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module).

**Comment by CommanderK5** [comment]
@bastelfreak Hey just noticed that secrets for this module has been generated, could you advice on how to incorporate that in to .sync.yaml? According to the docs this has to be 'masked' but I'm not sure how to do it.

**Comment by bastelfreak** [comment]
* added secret
* started a new release

**Comment by bastelfreak** [comment]
* https://forge.puppet.com/puppet/strongswan is now available
